version: "3"
services:
  wp:
    build: .
    ports:
      - 8010:80
      - 4430:443
    env_file:
      - wp.env
    environment:
      - "CUSTOM_HTA=${HTA2}"
    volumes:
      - ./wp-content:/var/www/html/wp-content
networks:
  default:
    external:
      name: services
